name: clang-format Check

# This runs on a push and checks if code format has been adhered to wrt clang-format
# It fails the CI if not done correctly
# Simply run the auto formatter to pass it

on:
  push:
    branches:
      - master
      - ci
      - test
      - pkb
      - qps
      - sp
      - staging
  pull_request:
    branches:
      - master

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.10.2
        with:
          clang-format-version: "15"
          check-path: "./Team06/Code06/src"
          fallback-style: "Google"
