name: clang-tidy-review

# This is a clang tidy linter, it DOES not resolve your code formats
# It just acts as a warning, and does not affect mergeability
# Only runs on PRs

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Optionally generate compile_commands.json

      - uses: ZedThree/clang-tidy-review@v0.10.0
        id: review
      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1
